### ISSUE TITLE
Since May 1, 2017 your website should be switched to new members area. If you still need your website follow instructions below.

### ISSUE THREAD

**Issue by keeganjk** [ShubhamBadal/email-spoofer#1]
Upon pressing `Submit, I am taken to a 000webhost page that says:

> Since May 1, 2017 your website should be switched to new members area.
> If you still need your website follow instructions below.

> No worries, we’ll help you with the migration process so that you could enjoy your website again! 
> All you need to do is follow these simple instructions:
> 
> Log in to old members area
> Backup all your files via FTP
> Backup your databases via phpMyAdmin
> Backup email by pushing your emails to Gmail
> Create account in new members area and setup your website from backup
> Still confused? Read migration tutorials in forum

**Comment by ShubhamBadal** [comment]
I've fixed the demo today.
