### ISSUE TITLE
Please guide me

### ISSUE THREAD

**Issue by X3eRo0** [ShubhamBadal/email-spoofer#2]
How to make a server configured for smtp .
Can I use xampp to do this?

**Comment by ShubhamBadal** [comment]
Doing it on localhost is possible but needs setup and is sometimes tricky. To keep it straightforward you can use a free PHP webhost that gives SMTP and mail support also. For example try 000webhost.

**Comment by X3eRo0** [comment]
Okay. Thank you

**Comment by X3eRo0** [comment]
Should I just upload the project files in my 000webhost server? Please give me hint so that I can go ahead

**Comment by ShubhamBadal** [comment]
Sure, you can send me your questions over email and we can discuss it there.
