### ISSUE TITLE
The issue is fixed

### ISSUE THREAD

**Issue by X3eRo0** [ShubhamBadal/email-spoofer#4]
In line 16 in index.html
Your HTML calls this PHP http://www.mailengine.ml/form-mailer.php.
So what I did is that I uploaded your code to my 000webhostapp.com and then moved form-mailer.php to the same directory as index.html and I edited the line 16 and removed http://www.mailengine.ml/form-mailer.php and I added just form-mailer.php and it worked

**Comment by legendarynacar** [comment]
@PulkitSingh256 can you make a live demo web page? cuz the current one is not working.

**Comment by ShubhamBadal** [comment]
@PulkitSingh256 Good! Yes that's the correct way and it will always work as long as the PHP host supports SMTP.

**Comment by ShubhamBadal** [comment]
@legendarynacar I've fixed the demo today.
