### ISSUE TITLE
Problems with delivering

### ISSUE THREAD

**Issue by ondrj** [ShubhamBadal/email-spoofer#6]
I don't know where the problem lies, but 5 out of 5 e-mail ISPs I have tried did not received any e-mail (neither in the 'spam' folder). Do you know where could be the problem? Note that I have not set up e-mail address on my own server, so this use case is not tested...

**Comment by ShubhamBadal** [comment]
You mean the sender email providers or receiver email providers? Since I no longer test my demo regularly, I am not sure if it still works.

But you can setup this code on PHP free hosts like 000webhosting yourself to send emails.
