### ISSUE TITLE
Getting an Error while Triggering an Email in PHP

### ISSUE THREAD

**Issue by mady143** [ShubhamBadal/email-spoofer#7]
Hi @ShubhamBadal ,
Actually I am trying to trigger an email through php script but i was unable to do this i need you help could you please help me to resolve this issue.
Actually ,
bellow is my php code for triggering an email could you please check, and let me know the error 

I am running this  code in localhost

$to = "xyz@gmail.com";
$subject = 'Testing PHP Mail';
$first_name = $_REQUEST['first_name'];
$last_name = $_REQUEST['last_name'];
$email = $_REQUEST['email'];
$phone = $_REQUEST['phone'];
$message = $_REQUEST['message'];
$htmlContent =' 

FirstName:    '.$first_name.',

LastName:     '.$last_name.',

Email:        '.$email.',

Message:      '.$message.'   ';

$headers = "From: ".$_REQUEST['email']."\r\n";
$headers .= "X-Mailer: PHP/" . phpversion() . "\r\n";
$headers .= "X-Priority: 1" . "\r\n";
$headers .= "MIME-Version: 1.0" . "\r\n";

if (mail($to, $subject, $message)) echo $headers.'Mail sent!';
  else echo 'Something went wrong...';

**Note:-here after running this script i am getting else statement**

Thanks & Regards,
Manikantha Sekhar...

**Comment by ShubhamBadal** [comment]
Sending mails require a mail server.

PHP Mail doesn't work on localhost unless you've configured SMTP server on your machine.

But it should run on a typical PHP hosting service since most of them offer mail services also.
